//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_Otopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_CTBL
    {
        public int ID { get; set; }
        public System.DateTime GirisZaman { get; set; }
        public Nullable<System.DateTime> CıkısZaman { get; set; }
        public bool Icerdemi { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public Nullable<int> KullanıcıID { get; set; }
        public int SinifID { get; set; }
        public string Plaka { get; set; }
        public int KatID { get; set; }
    
        public virtual KullanıcıTBL KullanıcıTBL { get; set; }
        public virtual SiniflarTBL SiniflarTBL { get; set; }
        public virtual KatTBL KatTBL { get; set; }
    }
}
