//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_Otopark
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtoParkDbEntities : DbContext
    {
        public OtoParkDbEntities()
            : base("name=OtoParkDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<G_CTBL> G_CTBL { get; set; }
        public virtual DbSet<KullanıcıTBL> KullanıcıTBL { get; set; }
        public virtual DbSet<OtoparkTBL> OtoparkTBL { get; set; }
        public virtual DbSet<SiniflarTBL> SiniflarTBL { get; set; }
        public virtual DbSet<YetkiTBL> YetkiTBL { get; set; }
        public virtual DbSet<KatTBL> KatTBL { get; set; }
    }
}
