//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_Otopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiniflarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiniflarTBL()
        {
            this.G_CTBL = new HashSet<G_CTBL>();
        }
    
        public int ID { get; set; }
        public string SinifAdi { get; set; }
        public decimal SınıfUcreti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_CTBL> G_CTBL { get; set; }
    }
}
